# Generated by Django 3.0.5 on 2022-04-25 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pisto_Alert_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '合宿リマインダーカテゴリー',
                'verbose_name_plural': '合宿リマインダーカテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Pisto_Alert_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '合宿リマインダータグ',
                'verbose_name_plural': '合宿リマインダータグ',
            },
        ),
        migrations.CreateModel(
            name='Pisto_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule1', models.DateTimeField(verbose_name='集合日')),
                ('schedule2', models.DateTimeField(verbose_name='最終日')),
                ('alert_time', models.DateTimeField(verbose_name='リマインダー日')),
                ('title', models.CharField(max_length=255, verbose_name='合宿名')),
                ('body', models.TextField(blank=True, help_text='HTMLタグは使えません。', verbose_name='リマインダー文')),
                ('published', models.BooleanField(default=True, verbose_name='公開する')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_reminder.Pisto_Alert_Category', verbose_name='合宿場所')),
                ('tags', models.ManyToManyField(blank=True, to='g_reminder.Pisto_Alert_Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '合宿リマインダー設定',
                'verbose_name_plural': '合宿リマインダー設定',
            },
        ),
    ]
