# Generated by Django 3.0.5 on 2021-02-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210222_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('Can_add_category', 'can add category'), ('Can_change_category', 'can change category'), ('Can_delete_category', 'can delete category'), ('Can_view_category', 'can view category'))},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('Can_add_post', 'can add post'), ('Can_change_post', 'can change post'), ('Can_delete_post', 'can delete post'), ('Can_view_post', 'can view post'))},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('Can_add_tag', 'can add tag'), ('Can_change_tag', 'can change tag'), ('Can_delete_tag', 'can delete tag'), ('Can_view_tag', 'can view tag'))},
        ),
    ]
