# Generated by Django 3.0.5 on 2021-02-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210222_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('Can_add_post', 'Can add post'), ('Can_change_post', 'Can change post'), ('Can_delete_post', 'Can delete post'), ('Can_view_post', 'Can view post'))},
        ),
    ]
