# Generated by Django 3.0.5 on 2021-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alert_alert_category_alert_tag_pisto_alert_pisto_alert_category_pisto_alert_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='pisto_alert',
            name='tags',
            field=models.ManyToManyField(blank=True, to='website.Alert_Tag', verbose_name='タグ'),
        ),
    ]
