# Generated by Django 3.0.5 on 2021-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_pisto_alert_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pisto_alert',
            name='alert_time',
            field=models.DateField(verbose_name='アラート日'),
        ),
        migrations.AlterField(
            model_name='pisto_alert',
            name='schedule1',
            field=models.DateField(verbose_name='集合日'),
        ),
        migrations.AlterField(
            model_name='pisto_alert',
            name='schedule2',
            field=models.DateField(verbose_name='最終日'),
        ),
    ]
