# Generated by Django 3.0.5 on 2021-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210314_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pisto_alert',
            name='alert_time',
            field=models.DateTimeField(verbose_name='アラート日'),
        ),
        migrations.AlterField(
            model_name='pisto_alert',
            name='schedule1',
            field=models.DateTimeField(verbose_name='集合日'),
        ),
        migrations.AlterField(
            model_name='pisto_alert',
            name='schedule2',
            field=models.DateTimeField(verbose_name='最終日'),
        ),
    ]
