# Generated by Django 3.0.5 on 2022-04-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '建て替え人登録',
                'verbose_name_plural': '建て替え人登録',
            },
        ),
        migrations.CreateModel(
            name='Receipt_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '建て替えレシートタグ',
                'verbose_name_plural': '建て替えレシートタグ',
            },
        ),
        migrations.CreateModel(
            name='Receipt_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='images', verbose_name='レシート')),
                ('date', models.DateTimeField(verbose_name='建て替え日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, help_text='HTMLタグは使えません。', null=True, verbose_name='備考')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
                ('published', models.BooleanField(default=True, verbose_name='公開する')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt_Category', verbose_name='建て替え人')),
                ('tags', models.ManyToManyField(blank=True, to='receipts.Receipt_Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '建て替えレシート登録',
                'verbose_name_plural': '建て替えレシート登録',
            },
        ),
    ]
