# Generated by Django 3.0.5 on 2022-04-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '資料庫カテゴリー',
                'verbose_name_plural': '資料庫カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '資料庫タグ',
                'verbose_name_plural': '資料庫タグ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, help_text='HTMLタグは使えません。', verbose_name='本文')),
                ('published', models.BooleanField(default=True, verbose_name='公開する')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, to='documents.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '資料庫',
                'verbose_name_plural': '資料庫',
            },
        ),
    ]
